version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SamAppEmailQeury"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i70qrl2zu6f7"
s3_prefix = "SamAppEmailQeury"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
